import { createClient } from "@/lib/supabase/server";
import { ReportGenerator } from "@/components/reports/report-generator";
import { getReportHistory } from "@/lib/actions/reports";
import { formatDateTime } from "@/lib/utils/date";
import { FileText } from "lucide-react";

export const dynamic = "force-dynamic";

const SIGNED_URL_EXPIRY = 3600;

export default async function ReportsPage() {
  const history = await getReportHistory();
  const clinicId = history.clinicId ?? "";

  const supabase = await createClient();
  const reportsWithUrls = await Promise.all(
    (history.reports ?? []).map(async (r) => {
      if (r.reportUrl && !r.reportUrl.includes("://")) {
        const { data } = await supabase.storage
          .from("documents")
          .createSignedUrl(r.reportUrl, SIGNED_URL_EXPIRY);
        return { ...r, reportUrl: data?.signedUrl ?? null };
      }
      return r;
    }),
  );

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-2xl font-semibold" style={{ color: "#3D2A25" }}>
          Compliance Reports
        </h1>
        <p className="text-sm" style={{ color: "#8B7D78" }}>
          Generate audit-ready compliance reports formatted for state board
          inspectors. Download as PDF or email directly.
        </p>
      </div>

      <section className="rounded-lg border p-6" style={{ borderColor: "#D9B7A7" }}>
        <h2 className="text-lg font-medium mb-4" style={{ color: "#3D2A25" }}>
          Generate New Report
        </h2>
        <p className="text-sm mb-4" style={{ color: "#8B7D78" }}>
          Creates a compliance audit report with staff credentials, status summary, upcoming renewals, and alert history. Report data is live — it reflects the current database state.
        </p>
        <ReportGenerator clinicId={clinicId} />
      </section>

      <section className="rounded-lg border p-6" style={{ borderColor: "#D9B7A7" }}>
        <h2 className="text-lg font-medium mb-4" style={{ color: "#3D2A25" }}>
          Report History
        </h2>

        {history.error ? (
          <p className="text-sm text-red-600">Failed to load report history.</p>
        ) : reportsWithUrls.length === 0 ? (
          <p className="text-sm" style={{ color: "#8B7D78" }}>
            No reports generated yet. Generate your first report above.
          </p>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b" style={{ borderColor: "#D9B7A7" }}>
                  <th className="py-2 text-left font-medium" style={{ color: "#3D2A25" }}>Date</th>
                  <th className="py-2 text-left font-medium" style={{ color: "#3D2A25" }}>Generated By</th>
                  <th className="py-2 text-right font-medium" style={{ color: "#3D2A25" }}>Action</th>
                </tr>
              </thead>
              <tbody>
                {reportsWithUrls.map((r) => (
                  <tr key={r.id} className="border-b" style={{ borderColor: "#F6E3D6" }}>
                    <td className="py-2" style={{ color: "#3D2A25" }}>
                      {formatDateTime(r.generatedAt)}
                    </td>
                    <td className="py-2" style={{ color: "#8B7D78" }}>
                      {r.generatedBy}
                    </td>
                    <td className="py-2 text-right">
                      {r.reportUrl ? (
                        <a
                          href={r.reportUrl}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="inline-flex items-center gap-1 text-sm font-medium"
                          style={{ color: "#9C6B5D" }}
                        >
                          <FileText className="h-4 w-4" />
                          Download
                        </a>
                      ) : (
                        <span className="text-sm" style={{ color: "#8B7D78" }}>
                          No file
                        </span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </section>
    </div>
  );
}
